### ISSUE TITLE
Error when saved file chooser paths do not exist later on

### ISSUE THREAD

**Issue by BobTheNerd10** [rhmodding/Treasury#2]
Whenever I open treasury and select 'Open extracted zlib directory', it shows this instead of opening up the file chooser.
![image](https://user-images.githubusercontent.com/48499877/96659559-19de7500-12fc-11eb-843e-e3f27fca171e.png)
![image](https://user-images.githubusercontent.com/48499877/96659616-38dd0700-12fc-11eb-9101-989b5ae7c014.png)
This has not happened before. Other programs like bread, RHRE and tickompiler all work without issue. I have redownloaded treasury multiple times because I thought it was a problem with the download.

**Comment by chrislo27** [comment]
Not enough info. Please make sure you are selecting a *folder* and not a zlib file. It would also be helpful if you could copy the contents of the error and upload it into a text file here.

**Comment by BobTheNerd10** [comment]
java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:238)
	at com.sun.glass.ui.CommonDialogs.showFolderChooser(CommonDialogs.java:226)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showDirectoryChooser(QuantumToolkit.java:1577)
	at javafx.stage.DirectoryChooser.showDialog(DirectoryChooser.java:103)
	at rhmodding.treasury.MainPane$$special$$inlined$apply$lambda$3.handle(MainPane.kt:44)
	at rhmodding.treasury.MainPane$$special$$inlined$apply$lambda$3.handle(MainPane.kt:21)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$6(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
	at java.lang.Thread.run(Unknown Source)

**Comment by BobTheNerd10** [comment]
Also I haven't opened anything, it crashes when I try and open the file chooser

**Comment by chrislo27** [comment]
This does seem like a bug, I will investigate. As a workaround, please try deleting this preferences file while Treasury is closed, and then re-open Treasury.

```
C:\Users\<your user name>\.rhmodding\treasury\prefs\prefs.json
```

You may have to enable viewing of hidden files and folders in File Explorer if you cannot see the `.rhmodding` folder.

**Comment by BobTheNerd10** [comment]
I think I found the issue. I moved the course data into a new folder, but treasury was still trying to look for the data in the old folder. Well, that's what I'm thinking by looking at the preferences. I deleted prefs.json and it works fine now.

**Comment by chrislo27** [comment]
Treasury searching for a non-existent folder to start the directory chooser in does seem like the problem and a fix will be made for it. Thanks for reporting!
